### ISSUE TITLE
TagField should replicate styling of TextField

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-tagfield#104]
As per title.

It's currently very unsightly consistent with lack of left & right padding

**Comment by robbieaverill** [comment]
I'm going to close this since we're going to be replacing the tag field rendering with a React based equivalent which will be controlled by the admin module in terms of styling/design. Doing that would make this issue obsolete. Since that issue is in progress at #110, doing this would be wasted effort.
